# Generated by Django 4.2.11 on 2026-04-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="cvv",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="expiry",
        ),
        migrations.AddField(
            model_name="submission",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="stripe_session_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
