# Generated by Django 4.2.11 on 2026-04-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_alter_card_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Card",
        ),
        migrations.DeleteModel(
            name="GradeReport",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
