# Generated by Django 4.2.11 on 2026-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0005_cardpricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("watching", "Watching"),
                    ("submitted", "Submitted for Grading"),
                    ("graded", "Graded"),
                    ("sold", "Sold"),
                ],
                default="watching",
                max_length=20,
            ),
        ),
    ]
