# Generated by Django 4.2.11 on 2026-04-14 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracking",
            "0007_cardpricing_image_url_cardpricing_tcg_player_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardpricing",
            name="date_recorded",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
