# Generated by Django 4.2.11 on 2026-04-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0008_alter_cardpricing_date_recorded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedcard",
            name="status",
            field=models.CharField(
                choices=[("watching", "Watching"), ("sold", "Sold")],
                default="watching",
                max_length=20,
            ),
        ),
    ]
