# Generated by Django 4.2.11 on 2026-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_trackedcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedcard',
            name='grade_tier',
            field=models.CharField(choices=[('ungraded', 'Ungraded'), ('near_mint', 'Near Mint'), ('lightly_played', 'Lightly Played'), ('moderately_played', 'Moderately Played'), ('heavily_played', 'Heavily Played'), ('damaged', 'Damaged'), ('psa_1', 'PSA 1'), ('psa_2', 'PSA 2'), ('psa_3', 'PSA 3'), ('psa_4', 'PSA 4'), ('psa_5', 'PSA 5'), ('psa_6', 'PSA 6'), ('psa_7', 'PSA 7'), ('psa_8', 'PSA 8'), ('psa_9', 'PSA 9'), ('psa_10', 'PSA 10')], default='ungraded', max_length=20),
        ),
    ]
