# Generated by Django 4.2.11 on 2026-04-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0010_alter_trackedcard_grade_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedcard",
            name="target_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
