# Generated by Django 4.2.28 on 2026-03-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='card_scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
