name: Build and Push Image

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Set lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/crinkle:latest" >> $GITHUB_ENV
        
      - name: Build image
        run: docker build -t $IMAGE_NAME ./crinkle_RENDER

      - name: Push image
        run: docker push $IMAGE_NAME
