name: Flake8 Linting

on:
  push:
  pull_request: # test on pull request to main branch
    types: [opened, reopened]

permissions:
  actions: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      
      # I format the code block as python so it highlights the error code, 
      # it's a bit hacky but better than looking at plain white text in my opinion.
      - name: Analysing the code with flake8
        run: |
          echo "## Flake8 Linting Report" > flake8_report.md
          echo \`\`\`python >> flake8_report.md
          flake8 --verbose --statistics $(git ls-files '*.py') | tee -a flake8_report.md
          echo \`\`\` >> flake8_report.md
      
      - name: Upload Flake8 Linting Report
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: flake8-linting-artifact
          path: flake8_report.md
      
      - name: Attach flake8 report to pull request
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          file-path: flake8_report.md

      - name: Cleanup Generated Report
        run: rm flake8_report.md
