# Generated by Django 4.2.11 on 2026-04-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0012_alter_card_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcollection",
            name="sort_order",
            field=models.CharField(default="name", max_length=400),
        ),
        migrations.AddField(
            model_name="cardcollection",
            name="value_threshold",
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=12
            ),
        ),
    ]
