# Generated by Django 4.2.11 on 2026-04-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0013_cardcollection_sort_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardcollection",
            name="sort_order",
            field=models.CharField(
                choices=[
                    ("name", "Name"),
                    ("date_scanned", "Date Scanned"),
                    ("grading_notes", "Grade"),
                    ("-name", "Name Descending"),
                    ("-date_scanned", "Date Scanned Descending"),
                    ("-grading_notes", "Grade Descending"),
                ],
                default="name",
                max_length=400,
            ),
        ),
    ]
