# Generated by Django 4.2.11 on 2026-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0014_alter_cardcollection_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="estimated_value",
            field=models.DecimalField(
                decimal_places=2, default=50, max_digits=12
            ),
        ),
    ]
