# Generated by Django 4.2.11 on 2026-04-03 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0016_alter_card_estimated_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="estimated_value",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
