# Generated by Django 4.2.11 on 2026-04-03 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0017_alter_card_estimated_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardcollection",
            name="value_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
