# Generated by Django 4.2.11 on 2026-04-06 00:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0018_alter_cardcollection_value_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ScannedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('name', models.CharField(default='Scanned Card', max_length=400)),
                ('grade', models.CharField(max_length=40)),
                ('picture_path', models.CharField(max_length=400)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
