# Generated by Django 4.2.11 on 2026-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0018_alter_cardcollection_value_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradereport",
            name="centering",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="gradereport",
            name="corners",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="gradereport",
            name="edges",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="gradereport",
            name="surface",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="gradereport",
            name="grade",
            field=models.TextField(null=True),
        ),
    ]
