# Generated by Django 4.2.11 on 2026-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0019_gradereport_centering_gradereport_corners_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradereport",
            name="centering",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="gradereport",
            name="corners",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="gradereport",
            name="edges",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="gradereport",
            name="grade",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="gradereport",
            name="surface",
            field=models.TextField(default=""),
        ),
    ]
