# Generated by Django 4.2.11 on 2026-05-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0020_alter_gradereport_centering_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="set_name",
            field=models.CharField(default="unknown", max_length=400),
        ),
        migrations.AddField(
            model_name="card",
            name="year",
            field=models.DateField(null=True),
        ),
    ]
