# Generated by Django 4.2.11 on 2026-05-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0021_card_set_name_card_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="year",
            field=models.CharField(default="unknown", max_length=400),
        ),
    ]
